import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { SiteFooter } from '@/components/marketing/site-footer';
import { SiteHeader } from '@/components/marketing/site-header';
import { TemplateCard } from '@/components/template-card';
import { Badge } from '@/components/ui/badge';
import { readDb } from '@/lib/store';

function normalize(value: string): string {
  return value.toLowerCase().replace(/\s+/g, '-');
}

export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> {
  const { category } = await params;
  const label = category.replace(/-/g, ' ');
  return {
    title: `${label} templates`,
    description: `Browse premium ${label} SaaS templates generated by SaaSForge AI.`
  };
}

export default async function TemplateCategoryPage({ params }: { params: Promise<{ category: string }> }) {
  const { category } = await params;
  const db = await readDb();
  const templates = db.templates.filter((template) => normalize(template.category) === category);
  if (templates.length === 0) notFound();

  return (
    <div>
      <SiteHeader />
      <main className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
        <Badge tone="info">SEO category page</Badge>
        <h1 className="mt-6 text-4xl font-semibold text-white">{templates[0]?.category} templates</h1>
        <p className="mt-4 max-w-3xl text-base leading-7 text-white/55">
          Deploy a {templates[0]?.category.toLowerCase()} product faster with premium UI, solid architecture, seeded data and the full SaaSForge AI workflow.
        </p>
        <div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">
          {templates.map((template) => (
            <TemplateCard key={template.id} template={template} />
          ))}
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
